[project]
name = "password-generator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "password-strength>=0.0.3.post2",
    "pyotp>=2.9.0",
    "streamlit>=1.44.0",
]
